### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by gersonkabum** [kabumhigor/KotlinMsProduto#1]
Sugiro adicionar no [.gitignore](https://github.com/kabumhigor/KotlinMsProduto/blob/master/.gitignore#L31) : `*.properties`
O arquivo [src/main/resources/application.properties](https://github.com/kabumhigor/KotlinMsProduto/blob/master/src/main/resources/application.properties#L3) possui as credenciais do bando de dados e não é bom deixar isso exposto no repositório. Ao adicionar essa linha no `.gitignore`, dar `commit` nele e remover o arquivo do repositorio. Após isso salve o arquivo `application.properties` com o seguinte nome: `application.properties.sample` e dentro dele adicione um simples passo a passo, ex:

```
[...]
# para funcionamento do MS copie esse arquivo e remova o .sample do final
# Arquivo usado para adicionar credenciais do banco de dados, coloque o endereço e senha bla bla
spring.datasource.url = <URL_DO_BANCO_DE_DADOS>
spring.datasource.username = <USERNAME>
spring.datasource.password = <SENHA>
[...]
```

com isso esse arquivo `application.properties.sample` irá ir para o repositório sem nenhuma credencial e estará com o passo a passo para o DEV executar o que for preciso. O proximo DEV que clonar o repo irá copiar o arquivo `application.properties.sample` e irá remover o `.simple` do final, adicionando as credenciais e fazendo com que o `.gitignore` não leve o arquivo para o repositorio novamente.

Como agora algumas pessoas também usam "Mac", é uma boa lembrar de colocar no `.gitignore`: `.DS_Store`. Em toda pasta que vc acessa com o finder ele cria esse demonio lá iuashaiush

___ 

Não sei como isso afeta a aplicação, mas algo me chamou atenção no tutorial e vi que não foi aplicado, segue o trecho:

> Now we need to make sure that the root class containing the main function is open. This is necessary because by default, all classes in kotlin are final and cannot be inherited from. For the spring framework however, classes annotated with @springbootapplication, @configuration etc need to be declared non final and this is the case for the root application class. Making this class open is easy, all we need to do is to add the open keyword to the class declaration.

[KotlinMsProdutoAppApplication.kt](https://github.com/kabumhigor/KotlinMsProduto/blob/master/src/main/kotlin/com/produto/kotlinmsprodutoapp/KotlinMsProdutoAppApplication.kt#L7)

___

Esse aki é só uma curiosidade. Nesse trecho do [Controller](https://github.com/kabumhigor/KotlinMsProduto/blob/master/src/main/kotlin/com/produto/kotlinmsprodutoapp/controller/ProdutoController.kt#L18), não é preciso explicitar o tipo de retorno, pois ele irá ser o mesmo tipo de `produtoRepository.findAll()`
```java
// Como esta
fun getAllProducts(): List<Produto> = produtoRepository.findAll()


// Assim tambem funciona e tem o mesmo tipo de retorno
fun getAllProducts() = produtoRepository.findAll()
```

**Comment by kabumhigor** [comment]
Apliquei todas as sugestões. Referente ao trecho do tutorial que você citou. Creio que tenha algo haver com a versão do framework ou do Kotlin. Quando coloquei a palavra open para deixar a classe aberta para extensão ela ficou com a cor cinza, como se não estivesse sendo utilizada. Por isso retirei
